language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1
    - 7.2
    - 7.4
    - 8.0snapshot
matrix:
    include:
        - php: 7.3
          env: LINT=1
        - php: 7.1
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_install:
    - phpenv config-rm xdebug.ini || true
	# Prevent '/home/travis/build/BooleanType/symfony_knpu_lorem_ipsum_bundle/composer.phar: Permission denied'
    # https://nofluffjuststuff.com/blog/brian_kotek/2013/06/grails_travis_ci_and_permission_denied
    - chmod +x composer.phar
    - composer self-update
    - composer self-update

install: composer update --prefer-dist $COMPOSER_FLAGS


script:
    - ./vendor/bin/simple-phpunit