language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 7.4
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

before_install:
	# Prevent '/home/travis/build/BooleanType/symfony_knpu_lorem_ipsum_bundle/composer.phar: Permission denied'
    # https://nofluffjuststuff.com/blog/brian_kotek/2013/06/grails_travis_ci_and_permission_denied
    - chmod +x composer.phar
    - composer self-update


install: composer update --prefer-dist $COMPOSER_FLAGS

script:
    - ./vendor/bin/simple-phpunit